/* =====================================================================
 *  SHARED PRESETS — the layouts this app itself carries
 * =====================================================================
 *
 * GENERATED by the Xenachord Designer's "Write Presets File" button.
 * 2026-08-28 16:56:01 · 5 presets
 *
 * This file IS the preset list. It lives beside index.html, so every copy of
 * the app carries it and anybody who opens the app sees the same presets. A
 * preset is one KEYBOARD — key types, widths, scale length, rotation — not a
 * rig: where a device stands and what its keys are called belong to the desk,
 * so a preset loads into any device of any rig without renumbering it.
 *
 * Written as a script rather than as .json because the app is meant to run by
 * opening index.html, and a file:// page cannot fetch() data.
 */
window.XENACHORD_PRESETS = {
  "Diatonic 12": {"rotation":0,"template":[null,null,null,null,null,null,null],"slots":{"0":["Full Sized Black"],"1":["Full Sized Black"],"3":["Full Sized Black"],"4":["Full Sized Black"],"5":["Full Sized Black"],"7":["Full Sized Black"],"8":["Full Sized Black"],"10":["Full Sized Black"],"11":["Full Sized Black"],"12":["Full Sized Black"],"14":["Full Sized Black"],"15":["Full Sized Black"],"17":["Full Sized Black"]},"autoScale":true,"scale":null,"preset":null,"origin":"centre","period":12},
  "Diatonic 17": {"rotation":0,"template":[null,null,null,null,null,null,null],"slots":{"0":["Split Gray First","Split Black Second"],"1":["Split Gray First","Split Black Second"],"3":["Split Gray First","Split Black Second"],"4":["Split Gray First","Split Black Second"],"5":["Split Gray First","Split Black Second"],"7":["Split Gray First","Split Black Second"],"8":["Split Gray First","Split Black Second"],"10":["Split Gray First","Split Black Second"],"11":["Split Gray First","Split Black Second"],"12":["Split Gray First"]},"autoScale":true,"scale":null,"preset":null,"origin":"centre","period":17},
  "Diatonic 19": {"rotation":0,"template":[null,null,null,null,null,null,null],"slots":{"0":["Split Gray First","Split Black Second"],"1":["Split Gray First","Split Black Second"],"2":["Split Gray First","Split Black Second"],"3":["Full Sized Gray"],"4":["Split Gray First","Split Black Second"],"5":["Split Gray First","Split Black Second"],"6":["Full Sized Gray"],"7":["Split Gray First","Split Black Second"],"8":["Split Gray First","Split Black Second"],"9":["Split Gray First","Split Black Second"],"10":["Full Sized Gray"],"-1":["Full Sized Gray"]},"autoScale":true,"scale":null,"preset":null,"origin":"centre","period":19},
  "Octatonic 12": {"rotation":0,"template":[null,null,null,null,null,null,null],"slots":{"0":["Full Sized Black"],"2":["Full Sized Black"],"4":["Full Sized Black"],"6":["Full Sized Black"],"8":["Full Sized Black"],"10":["Full Sized Black"],"12":["Full Sized Black"],"14":["Full Sized Black"],"16":["Full Sized Black"],"18":["Full Sized Black"],"20":["Full Sized Black"]},"autoScale":true,"scale":null,"preset":null,"origin":"centre","period":12},
  "Whole-Tone 12": {"rotation":0,"template":[null,null,null,null,null,null,null],"slots":{"0":["Full Sized Black"],"1":["Full Sized Black"],"2":["Full Sized Black"],"3":["Full Sized Black"],"4":["Full Sized Black"],"5":["Full Sized Black"],"6":["Full Sized Black"],"7":["Full Sized Black"],"8":["Full Sized Black"],"9":["Full Sized Black"],"10":["Full Sized Black"],"11":["Full Sized Black"],"12":["Full Sized Black"],"13":["Full Sized Black"],"14":["Full Sized Black"],"15":["Full Sized Black"]},"autoScale":true,"scale":null,"preset":null,"origin":"centre","period":12},
};
